### ISSUE TITLE
Mentor team duplication

### ISSUE THREAD

**Issue by peter-drew** [robocupjunioraustralia/RCJA_Registration_System#31]
Teams are often duplicated between events (eg regionals then states) and a way to duplicate teams quickly is needed for mentors. Probably a checkbox on the teams view which allows mentors to select which teams to duplicate, then a model which asks which open event to duplicate the teams in.

**Comment by evanbailey** [comment]
This should work so that when mentors are adding teams, they can pick from existing (e.g. searchable dropdown) of their previous teams. Should pull through linked students as well.

**Comment by evanbailey** [comment]
#30 required first (team/stu many to many implementation)

**Comment by peter-drew** [comment]
Closed in #629
