### ISSUE TITLE
Consider invoiceDate behaviour

### ISSUE THREAD

**Issue by peter-drew** [robocupjunioraustralia/RCJA_Registration_System#371]
Currently invoiceDate is set the first time the invoice is viewed, doesn't change if the invoice changes as teams are added or removed. What should this behaviour be?

For that matter, should we keep track of all changes to the invoice amount?

**Comment by Dalordish** [comment]
Hasn't been an issue in the past - ideal behaviour is new invoices on modification, but that's a lot of work

**Comment by evanbailey** [comment]
Invoice date can be payment due date.

**Comment by peter-drew** [comment]
Set invoiceDate to payment close date on invoice creation. If the mentor views the invoice and the payment date is in the future, set it to the current date.
