### ISSUE TITLE
Add venue field to the add event page in admin

### ISSUE THREAD

**Issue by evanbailey** [robocupjunioraustralia/RCJA_Registration_System#426]
Please move this to the first page of the create event workflow. THis will avoid the generic image showing which was confusing.

**Comment by peter-drew** [comment]
See also #435

**Comment by peter-drew** [comment]
See #466 and 9ccf741a67a67efab5014f73a63556497066e671
Currently not easy to fix this. Probably part of the new event admin.

**Comment by evanbailey** [comment]
Nobody is complaining, no need to do.
