### ISSUE TITLE
Filter schools to mentor on admin team page

### ISSUE THREAD

**Issue by evanbailey** [robocupjunioraustralia/RCJA_Registration_System#429]
Dropdown not filtering to schools the choosen mentor is part of.

**Comment by evanbailey** [comment]
Although I do see it is automatic with mentor...I should read the instructions more througherly.

**Comment by peter-drew** [comment]
This is automatic for a mentor based on currently selected school. On the admin page there is the same problem with #428 that the mentor is not know when the page is initially loaded. It would therefore be possible to filter on edits but would require JS to do for adds - and if it was implemented server side for edits, it would make changing the mentor or school very difficult.

Currently if you leave the school blank and the mentor only has one school the team is set to that school. This is documented in (admittedly small) text above the field, could look at making this more obvious.
![image](https://user-images.githubusercontent.com/10608341/96524805-fd731600-12c4-11eb-83c4-bc5ece9d5d2e.png)

**Comment by evanbailey** [comment]
Now I have read the text, this works quite well.

**Comment by peter-drew** [comment]
Like with #428, this can be improved in the new event admin UI.

**Comment by evanbailey** [comment]
Works ok ATM.
