### ISSUE TITLE
Restrict team, mentor, school, campus and student names to ASCII

### ISSUE THREAD

**Issue by peter-drew** [robocupjunioraustralia/RCJA_Registration_System#450]
Is this desired?

**Comment by evanbailey** [comment]
Yes

**Comment by evanbailey** [comment]
this doesn't seem to have been an issue, i am currently cleaning out any ' via excel - so i think this can be closed.

**Comment by evanbailey** [comment]
This is required again.

We need to clean out team, school, mentor and student names to only be A-Z/a-z and -. No ", ' or other chars.
