### ISSUE TITLE
Improve 403 for visiting an event page before regos open

### ISSUE THREAD

**Issue by ZMcWilliam** [robocupjunioraustralia/RCJA_Registration_System#528]
As (published) events that have not reached their registrations open date still show on the main site, users are able to visit the event page before registrations are open. 
This currently throws a 403 page that does not inform the user why they are unable to access it.
![image](https://user-images.githubusercontent.com/36472285/123222465-527dc080-d513-11eb-8862-81c83b7bd598.png)

Showing a 403 page (or just the normal event page) with some information on when registrations will open would prevent confusion.

Also if an event page is viewed by an admin before registrations are open, the message at the bottom states the wrong thing

**Comment by peter-drew** [comment]
Will look at that logic and see what can be done to improve.

> Also if an event page is viewed by an admin before registrations are open, the message at the bottom states the wrong thing

@ZMcWilliam Which message are you referring to here?

**Comment by ZMcWilliam** [comment]
The message is minor, it's just the message of "Registration for this event has closed." whereas it hasn't opened yet

I have noticed that published events are hidden on the entry site before the registration open date, the fix could be to modify the script on the main website to not show published events before registrations open however I think it would be preferable to show users the page beforehand anyway to give schools/mentors more time to plan ahead

I may just be thinking about the use case of the registration open date wrong...

**Comment by peter-drew** [comment]
> Can we simply change the code on the main website to not hyperlink if the event hasn't opened for registration yet?

Was this ever done? Either way I will change the permissions on the registration system as Zac suggested.

**Comment by evanbailey** [comment]
I don't think the website was ever updated to this.
