### ISSUE TITLE
Cannot create state as both available for registration and global. 

### ISSUE THREAD

**Issue by evanbailey** [robocupjunioraustralia/RCJA_Registration_System#533]
Need for this has materialised as National is now running events in its own right and will likely do so again in the future. 

Should be able to set national to global, show on website, and registration available.

**Comment by peter-drew** [comment]
Currently both the ability for a user to be associated to a particular state and the ability to connect an event to a particular state is tied to 'registration'. We don't want users associated to the National state so will need to create a new attribute to define global events, or change the behaviour for Global states.
