### ISSUE TITLE
$0 invoices showing

### ISSUE THREAD

**Issue by evanbailey** [robocupjunioraustralia/RCJA_Registration_System#575]
Invoices that are $0 show not show (e.g. when all teams or workshop attendees are deleted), and the system should not generate invoices for workshops or competitions that have a $0 entry fee.

**Comment by peter-drew** [comment]
#606 stops $0 invoices showing on mentor frontend and they won't be created for free events. They will still show on the admin because any change to fix this with the current architecture will make that page incredibly slow.
