### ISSUE TITLE
Admin UI

### ISSUE THREAD

**Issue by Dalordish** [robocupjunioraustralia/RCJA_Registration_System#9]

**Comment by Dalordish** [comment]
I'm unsure as to the extent to which this is really useful if it's just a small css tweak like changing including/changing the main navbar into the admin navbar (seeing as the two views, user/mentor and admin, have fundamentally different functionality).

It *may* also be a good idea to have the admin view differently styled anyway, because it signifies a change in context - that said, it's somewhat jarring going from one interface to another, so maybe the difference in style is too big. Unsure.

I think there might be some utility to be gained by creating basic admin views for things like Event creation/management, where less technically skilled regional administrators might want to just do basic things (also likely where more custom functionality is going to be required anyway, i.e. WYSIWG editor for site content, invoice generation, etc), in which case integrating that into admin through custom navigation might be quite useful.

**Comment by Dalordish** [comment]
Better to have a separate frontend for low skill/perm admins

**Comment by Dalordish** [comment]
Event centered UI
teams, etc

**Comment by evanbailey** [comment]
Everyone is happy with current UI.
